services:
  website:
    build:
      context: ./app-web
    ports:
      - 80:80


  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_DB: postgis-demo
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgis-data:/var/lib/postgresql/data

  flask:
    build:
      context: ./server
    depends_on:
      - postgis
    command: sh -c "flask --app ~/server/app init-db && waitress-serve --port=5000 --call app:create_app"


volumes:
  postgis-data:
  pgadmin-data: