services:
  postgis:
    image: postgis/postgis
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: 12345678
    volumes:
        - postgis-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    depends_on:
      - postgis
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=12345678


volumes:
  postgis-data:
  pgadmin-data: